pipeline {
    agent any

    environment {
        REGISTRY = "esmejia277"
        IMAGE = "simple-app"
        TAG = "v${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/esmejia277/cicd-jenkins-k8s.git'
            }
        }

        stage('Build & Push Docker image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'Dockerhub',
                                                  usernameVariable: 'DOCKER_USER',
                                                  passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker build -t ${REGISTRY}/${IMAGE}:${TAG} app
                        docker push ${REGISTRY}/${IMAGE}:${TAG}
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh """
                helm upgrade --install simple-api-dev app/k8s/helm/simple-api \
                    -f app/k8s/helm/simple-api/values-dev.yaml \
                    --set image.tag=${BUILD_NUMBER} \
                    -n dev
                """
            }
        }
        
    }
}
