pipeline {
    agent any

    triggers {
        githubPush()
    }

    environment {
        REGISTRY = "esmejia277"
        IMAGE = "simple-app"
        TAG = "v${BUILD_NUMBER}"
    }

    stages {
        stage('Build & Push Docker image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'Dockerhub',
                                                  usernameVariable: 'DOCKER_USER',
                                                  passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        // Normaliza el nombre de la rama para usarlo en el tag
                        def branch = env.BRANCH_NAME.replaceAll('/', '-')

                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                            docker build -t ${REGISTRY}/${IMAGE}:${TAG}-${branch} app
                            docker push ${REGISTRY}/${IMAGE}:${TAG}-${branch}
                        '''
                    }
                }
            }
        }

        stage('Deploy with Helm') {
            steps {
                script {
                    def branch = env.BRANCH_NAME.replaceAll('/', '-')

                    if (branch.startsWith("feature-")) {
                        echo "Deploying feature branch: ${branch}"
                        sh """
                        helm upgrade --install ${IMAGE}-${branch} app/k8s/helm/simple-api \
                            -f app/k8s/helm/simple-api/values-feature.yaml \
                            --set image.repository=${REGISTRY}/${IMAGE} \
                            --set image.tag=${TAG}-${branch} \
                            -n feature
                        """
                    } else if (branch == "origin-master") {
                        echo "Deploying to PROD"
                        sh """
                        helm upgrade --install ${IMAGE}-prod app/k8s/helm/simple-api \
                            -f app/k8s/helm/simple-api/values-prod.yaml \
                            --set image.repository=${REGISTRY}/${IMAGE} \
                            --set image.tag=${TAG}-${branch} \
                            -n prod
                        """
                    } else {
                        echo "Branch ${branch} not configured for deployment"
                    }
                }
            }
        }
    }
}
